Delivery\TestBundle\Entity\Grupo:
    type: entity
    table: fos_group
    repositoryClass: Delivery\TestBundle\Repository\GrupoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
